### ISSUE TITLE
No Decks Show Up in the Deck Selector Dropdown Menu

### ISSUE THREAD

**Issue by geckolocation** [feoff3/roll20-deck-creator#1]
I'm using firefox
I've followed the instructions in the readme, except for step 5 of the firefox installation because greasemonkey has updated since it was written; this section seems to be covered in the "==UserScript==" part at the top of the code, but on the off chance this portion isn't accounted for, i also tried it with "https://app.roll20.net/editor/" in the "user includes" box under "user script options" for this script, after looking at the options available by clicking the greasemonkey extension icon

i can see the "Create Cards from Library Images" button, as well as the "Deck:" dropdown menu and the "Image RegExp:" text field, but nothing appears in the dropdown menu when i click it

i've reloaded the page, made new decks, and new games, in all conceivable configurations, i've also turned off all my other extensions on the off chance that there was some weird conflict somewhere

have i done something wrong?
and/or, have there been any changes to roll20/greasemonkey/firefox that would have caused this problem?

**Comment by feoff3** [comment]
Thanks for posting the issue.

It has been a while since I published the script, and something may have
changed since then in any of apps involved.

Feel free to ping me back in this issue in a week or two - I may have some
spare time to take a closer look to check what is wrong...

ср, 4 дек. 2019 г., 5:35 geckolocation <notifications@github.com>:

**Comment by geckolocation** [comment]
@feoff3 it's been a couple weeks

i fiddled with the code a bit to see if i could figure anything out, i think that the problem is with 'Campaign.decks.backboneFirebase.collection.models', which doesn't seem to resolve to anything, but i don't know enough to fix the problem myself

if you have some time i would appreciate it if you would look into this

either way, thank you for your time and effort

**Comment by Kerredai** [comment]
I'm having the same issue with a clean install of the most recent Firefox; refreshing and/or creating new decks doesn't help.

**Comment by feoff3** [comment]
Thanks for letting me know. It is highly possible something has changed in
roll20 impl since I made my script... The whole javascript object model of
the app may have changed since then. (The script relies on some internal
structure of roll20 as desired functionality is not provided via official
api)

сб, 21 дек. 2019 г., 5:44 Kerredai <notifications@github.com>:

**Comment by feoff3** [comment]
Well, the script works if I use it with TemperMonkey on Firefox.
It seems like GreaseMonkey doesn't work for some reason.

Please try installing TemperMonkey on Firefox and try again.

**Comment by geckolocation** [comment]
yup worked perfectly with TemperMonkey, thank you
